#!/bin/env bash

help() {
	echo "Usage:"
	echo " $0 start - Start the application: init the database container, run the ETL-LAR application, and start the web server."
	echo " $0 stop   - Stop the ETL-LAR services and remove containers."
	echo " $0 run   - Run the ETL-LAR application in command line mode."
	echo " $0 app  - Run the ETL-LAR application in web server mode."
	echo " $0 help   - Display this help message"
	exit 1
}

verify_docker() {
	if [[ ! -x "$(command -v docker)" ]]; then
		echo "Error: Docker is not installed." >&2
		return 1
	fi
	return 0
}

verify_docker_compose() {
	if [[ ! -x "$(command -v docker-compose)" && ! -x "$(command -v docker compose)" ]]; then
		echo "Error: docker-compose is not installed." >&2
		return 1
	fi
	return 0
}

verify_env() {
	if [[ -f .env ]]; then
		echo ".env file found: Using environment variables from .env file."
		source .env
	else
		echo "Error: .env file not found." >&2
		if [[ -f .env.example ]]; then
			cp .env.example .env
			echo "A .env file has been created from .env.example. Please review and update the environment variables as needed." >&2
		else
			echo "Please create a .env file with the required environment variables." >&2
			echo "SEE README.md for more details." >&2
			return 1
		fi
	fi
	return 0
}


verify_required_python_packages() {
	if [[ -f requirements.txt ]]; then
		echo "Checking for required Python packages..."
		while IFS= read -r package; do
			if ! pip show "$package" > /dev/null 2>&1; then
				printf "Error: Required Python package '\033[1m%s\033[0m' is not installed.\n" "$package" >&2
				printf "Please install the required packages using: \033[1mpip install -r requirements.txt\033[0m\n" >&2
				return 1
			fi
		done < requirements.txt
		printf "\033[1mAll required Python packages are installed.\033[0m\n"
	else
		printf "\033[1mNo requirements.txt file found. Skipping Python package verification.\033[0m\n"
		return 1
	fi
	return 0
}

database_init() {
	if [[ ! verify_docker || ! verify_docker_compose ]]; then
		exit 1
	fi
	printf "\033[1mInitializing database container...\033[0m\n"
	docker-compose up -d && printf "\033[1mDatabase container started successfully.\033[0m\n" || { printf "\033[1mFailed to start database container.\033[0m\n" >&2; exit 1; }
}

run() {
	if [[ ! verify_env ]]; then
		exit 1
	fi
	if [[ ! verify_required_python_packages ]]; then
		exit 1
	fi
	printf "\033[1mRunning ETL-LAR application in command line mode...\033[0m\n"
	python ./src/main.py 
}

app() {
	if [[ ! verify_env ]]; then
		exit 1
	fi
	if [[ ! verify_required_python_packages ]]; then
		exit 1
	fi
	printf "\033[1mRunning ETL-LAR application in web server mode...\033[0m\n"
	python -m streamlit run ./src/dashboard.py --server.port 8501
}

start() {
	database_init
	echo "1) CLI application"
	echo "2) WEB application"
	read -rp "Enter your choice (default: WEB): " choice
	case $choice in
		1) run ;;
		2) app ;;
		*) app ;;
	esac
}

stop () {
	printf "\033[1mStopping ETL-LAR application...\033[0m\n"
	docker-compose down && printf "\033[1mETL-LAR application stopped successfully.\033[0m\n" || { printf "\033[1mFailed to stop ETL-LAR application.\033[0m\n" >&2; exit 1; }
}


if [[ -z "$1" ]]; then
	help
fi

if [[ "$1" == "start" ]]; then
	start
elif [[ "$1" == "stop" ]]; then
	stop
elif [[ "$1" == "run" ]]; then
	run
elif [[ "$1" == "app" ]]; then
	app
elif [[ "$1" == "help" ]]; then
	help
elif [[ "$1" == "database" ]]; then
	database_init
else
	echo "Error: Invalid command '$1'" >&2
	help
fi